---
title: "課題2:Debugging and Improving R Code"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}

library(pacman)
pacman::p_load(tidyverse, here, estimatr)

```

## Problem 1: NA Handling

```{r}
df <- tibble(
  col1 = sample(c(NA, 1), size = 100, replace = TRUE)
) %>% 
  mutate(
    # is_na = if_else(col1 == NA, TRUE, FALSE)
    # col == NA の部分をis.na(col1)に変更
    is_na = if_else(is.na(col1), TRUE, FALSE)
  )
```

## Problem 2: Column Selection and package Compatibiity

```{r}
df_population <- # readr::read_csv(here::here("assignment23_data", "raw", "population_ps2.csv"))
  # hereを使用するとこのファイルからの相対パスにるので、.Rprojファイルからの絶対パスの方が良い
  readr::read_csv("data/assignment23_data/raw/population_ps2.csv")

list_vars <- # dplyr::select_vars(vars = names(df_population), contains("name"))
  # select_varsはもう使用できないのでstr_subsetを使用する
  stringr::str_subset(names(df_population), "name")

df_population %>% 
  select(list_vars)
```

## Problem 3: Log Transformation

```{r}
df_lm <- df_population %>% 
  arrange(city_name, year) %>% 
  mutate(
    change_rate = (log(population) - dplyr::lag(log(population), n = 20)),
    .by = city_id
  ) %>% 
  dplyr::filter(year == 2015)

lm(log(change_rate) ~ log(population), data = df_lm)
```

## Problem 4: Reusable ggplot Code

```{r}
set.seed(111)
df <- tibble(
  col_1 = seq(1, 10),
  col_2 = seq(11, 20) + rnorm(n = 10, 0, 1),
  col_3 = seq(30, 21) + rnorm(n = 10, 1, 1)
)

plot_col_12 <- ggplot(df, aes(x = col_1, y = col_2)) +
  geom_point() +
  theme_minimal()

plot_col_13 <- ggplot(df, aes(x = col_1, y = col_3)) +
  geom_point() +
  theme_minimal()

plot_col_23 <- ggplot(df, aes(x = col_2, y = col_3)) +
  geom_point() +
  theme_minimal()

# 列名を引数として受け取れるような関数plot_colを作成する

plot_col <- function(x1, x2){
  ggplot(df, aes(x = {{x1}}, y = {{x2}})) +
    geom_point() +
    theme_minimal()
}

plot_col(col_1, col_2)
plot_col(col_1, col_3)
plot_col(col_2, col_3)
```

## Problem 5: Dynamic Column Naming in mutate()

```{r}
df <- tibble(
  a = seq(1, 10)
)

add_column <- function(df, is_name) {
  df <- df %>% 
    mutate(
      # is_name = if_else(a > 5, TRUE, FALSE)
      # これだとis_nameという列が作成されるので、:=を使用することで変数の中身を新しい列名とする
      {{is_name}} := if_else(a > 5, TRUE, FALSE)
    )
  
  return(df)
}

add_column(df, "higher") %>% 
  dplyr::filter(higher == TRUE)
```

## Problem 6: Simplyfying Model Code with Formula Generation

```{r}
set.seed(111)
df <- tibble(
  y = seq(101, 200),
  x_1 = seq(1, 100) + rnorm(n = 100, 0, 1),
  x_2 = sample(c(0, 1), 100, replace = TRUE),
  x_3 = seq(50, 149) + rnorm(n = 100, 0, 1)
)

linear_models <- function(data) {
  
  model_1 <- lm_robust(y ~ x_1, data = data)
  model_2 <- lm_robust(y ~ x_1 + x_2, data = data)
  model_3 <- lm_robust(y ~ x_2, data = data)
  model_4 <- lm_robust(y ~ x_1 + x_2 + x_3, data - data)
  
  list_output <- list(
    model_1 = model_1,
    model_2 = model_2,
    model_3 = model_3,
    model_4 = model_4
  )
  
  return(list_output)
}

res <- df %>% linear_models()

# より柔軟で簡潔な書き方
```


